M48
; DRILL file {KiCad 7.0.2} date Mon Jun 26 18:46:50 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-26T18:46:50-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X96.881Y-91.602
X110.881Y-69.403
X124.881Y-91.602
T2
X87.031Y-133.482
X212.031Y-70.983
T0
M30
